default:
	@just --list

build: build-dev

build-dev:
	cargo build --workspace

build-prod:
	cargo build --workspace --release

run: run-dev

run-dev:
	cargo run -p host

run-prod:
	cargo run -p host --release

run-native-dev:
	NO_RISC0=1 cargo run -p host

run-native-prod:
	NO_RISC0=1 cargo run -p host --release

manual: manual-dev

manual-dev: run-dev

manual-prod: run-prod

manual-native-dev: run-native-dev

manual-native-prod: run-native-prod

salsa: manual-dev

salsa-dev: manual-dev

salsa-prod: manual-prod

salsa-native-dev: manual-native-dev

salsa-native-prod: manual-native-prod

test:
	cargo test --workspace

clean:
	cargo clean
