[defaults]
trials = 1
timeout_sec = 1000
output_root = "artifacts/benchmarks"

[[targets]]
id = "aes-r0"
enabled = true
workdir = "aes-r0"
command = ["cargo", "run", "-p", "host", "--release", "--", "--json"]

[[targets]]
id = "aes-r0-optimised"
enabled = true
workdir = "aes-r0-optimised"
command = ["cargo", "run", "-p", "host", "--release", "--", "--json"]

[[targets]]
id = "salsa-r0"
enabled = true
workdir = "salsa-r0"
command = ["cargo", "run", "-p", "host", "--release", "--", "--json"]

[[targets]]
id = "lowmc-r0"
enabled = true 
workdir = "lowmc-r0"
command = ["cargo", "run", "-p", "host", "--release", "--", "--json"]

[[targets]]
id = "lowmc-optimised"
enabled = true 
workdir = "low-mc-optimised"
command = ["cargo", "run", "-p", "host", "--release", "--", "--json"]

[[targets]]
id = "operation-bnchmrk-r0"
enabled = true
workdir = "operation-bnchmrk-r0"
command = ["cargo", "run", "-p", "host", "--release", "--", "--json", "--iterations", "100"]
