default:
	@just --list

build: build-dev

build-dev:
	cargo build --workspace

build-prod:
	cargo build --workspace --release

run: run-dev

run-dev:
	cargo run -p host

run-prod:
	cargo run -p host --release

run-native-dev:
	NO_RISC0=1 cargo run -p host

run-native-prod:
	NO_RISC0=1 cargo run -p host --release

ctr: ctr-dev

ctr-dev: run-dev

ctr-prod: run-prod

ctr-native-dev: run-native-dev

ctr-native-prod: run-native-prod

encrypt: encrypt-dev

encrypt-dev: run-dev

encrypt-prod: run-prod

encrypt-native-dev: run-native-dev

encrypt-native-prod: run-native-prod

test:
	cargo test --workspace

clean:
	cargo clean
