default: all

all: build

build:
	latexmk -pdf -interaction=nonstopmode -synctex=1 -f fyp-report.tex

preview:
	latexmk -pdf -pvc -interaction=nonstopmode -synctex=1 -f fyp-report.tex

view: build
	open fyp-report.pdf

archive: build
	rm -f archive.zip
	zip -r archive.zip Figures/ Justfile *.cls *.tex *.bib fyp-report.pdf -x "*.svn*"

clean:
	latexmk -C
	rm -f fyp-report.pdf *.synctex.gz
